//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendence
    {
        public int EmpCode { get; set; }
        public System.DateTime AttDate { get; set; }
        public string InHour { get; set; }
        public string InMinute { get; set; }
        public string OutHour { get; set; }
        public string OutMinute { get; set; }
        public string AttStatus { get; set; }
        public string TotalRegularHour { get; set; }
        public string Remarks { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
