//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryCreate
    {
        public int SalCreateCode { get; set; }
        public int EmpCode { get; set; }
        public string BasicAmt { get; set; }
        public string HouseRentAmt { get; set; }
        public string MedicalAmt { get; set; }
        public string OtherAllAmt { get; set; }
        public string GrossAmt { get; set; }
        public Nullable<int> MonthNo { get; set; }
        public Nullable<int> YearNo { get; set; }
        public Nullable<System.DateTime> SFromDT { get; set; }
        public Nullable<System.DateTime> SToDT { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
